# docker-compose -f docker-compose.yml -f docker-compose.dev-overrride.yml up --build
version: '3.4'
services:
  server:
    image: $server_image:dev
    build:
      context: .
      target: dev
    volumes:
      - ./dist:/app/dist
      - ./nginx:/app/nginx
