#!/usr/bin/env sh
script_dir () { (a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; echo "$a"); }
load_env () { [ -f .env ] && for a in $1; do
	export $a="$(cat .env | grep $a= | sed -e "s/.*=//g")"; done; }

cd "$(script_dir)"
load_env "env"

req_image () {
	name="$1"; build_path="$2";
	if ! (docker images | grep "$name "); then
		echo "$name missing"; exit
		# (cd "$build_path" && docker build -t "$name" .)
	fi
}

if [ "$env" = "dev" ]; then
	req_image "leonardpauli/docs-nginx-base" "../.."
	req_image "leonardpauli/docs-ssl-manager" "../../../../ssl/ssl-manager"
	docker-compose -f docker-compose.yml -f docker-compose.dev-override.yml up --build
elif [ "$env" = "prod" ]; then
	docker-compose up --build -d
else
	echo "unknown env '$env', check ./.env"
fi
