version: '2'

services:
  nginx:
    image: leonardpauli/docs-nginx-example
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./ssl:/etc/nginx/ssl
    ports: ["80:80", "443:443"]
    networks:
      default:
        ipv4_address: 10.100.0.2

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1
