#!/usr/bin/env sh
script_dir () { (a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; echo "$a"); }
load_env () { [ -f .env ] && for a in $1; do
	export $a="$(cat .env | grep $a= | sed -e "s/.*=//g")"; done; }

cd "$(script_dir)"
load_env "env"

if [ "$env" = "dev" ]; then
	docker-compose -f docker-compose.yml -f docker-compose.dev-override.yml up --build
elif [ "$env" = "prod" ]; then
	docker-compose up --build -d
else
	echo "unknown env '$env', check ./.env"
fi
