#!/usr/bin/env sh
env=${env:-dev} # see terminal/lib.sh for load_env
if [ "$env" = "dev" ]; then
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
elif [ "$env" = "prod" ]; then
docker-compose -f docker-compose.yml up # -d
else echo "unknown env '$env', check .env"; fi
