#!/usr/bin/env sh
script_dir () { (a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; echo "$a"); }
load_env () { [ -f .env ] && for a in $1; do
	export $a="$(cat .env | grep $a= | sed -e "s/.*=//g")"; done; }

cd "$(script_dir)"
load_env "env"

if [ "$env" = "dev" ]; then
	req_image="leonardpauli/docs-nginx-base"
	# if ! (docker images | grep "$req_image "); then
	# 	echo "$req_image missing, building it"
		(cd ../.. && docker build -t leonardpauli/docs-nginx-base .)
		(cd ../../../../ssl/ssl-manager && docker build -t leonardpauli/docs-ssl-manager .)
	# fi
	docker-compose -f docker-compose.yml -f docker-compose.dev-override.yml up --build
elif [ "$env" = "prod" ]; then
	docker-compose up --build -d
else
	echo "unknown env '$env', check ./.env"
fi
