version: '3'
services:
  server:
    image: httpd:2.4-alpine
    volumes:
      - ./data/ssl/acme/.well-known/acme-challenge:/usr/local/apache2/htdocs/.well-known/acme-challenge
    ports: ["80:80"]
    
  ssl-manager:
    image: leonardpauli/docs-ssl-manager
    build: ..
    # entrypoint: ["tail", "-f", "/dev/null"]
    volumes: ["data/ca:/data/ca", "data/ssl:/data/ssl"]
    environment:
      ssl_local_domains: "${domain_base}.localhost,local.$domain_prod"
      ssl_local_displayname: "$domain_base (local)"
      ssl_prod_create: "$production"
      ssl_prod_domains: "$domain_prod"
      ssl_prod_displayname: "$domain_base"
      ssl_prod_notify_email: "webmaster@$domain_prod"
      ssl_prod_stageing: "false"
    depends_on:
      - server
