version: '3'
services:
  server:
    image: nginx:1.13-alpine
    volumes:
      - ./data/ssl/acme/webroot/.well-known/acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge
    ports: ["80:80"]
    depends_on:
      - ssl-manager
    
  ssl-manager:
    image: leonardpauli/docs-ssl-manager
    build: ..
    # entrypoint: ["tail", "-f", "/dev/null"]
    volumes: ["./data/ca:/data/ca", "./data/ssl:/data/ssl"]
    environment:
      # ssl_local_renew_schedule: '*/1 * * * *'
      ssl_dhparam_create: 'false'
      ssl_local_domains: "${domain_base}.localhost,local.$domain_prod"
      ssl_prod_create: "$production"
      ssl_prod_domains: "$domain_prod"
      ssl_prod_notify_email: "webmaster@$domain_prod"
      ssl_prod_stageing: "false"
