#!/usr/bin/env sh

script_dir () { (a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; echo "$a"); }
load_env () { while read a <&3; do [ "${a#'#'}" = "$a" ] && [ ! -z "$a" ] && export "$a"; done 3< "${1:-.env}"; }

cd "$(script_dir)"
if ! load_env; then # lpdocs dev_window_setup
	echo 'No .env file created'; echo 'Please see docs/setup.rim/"get running"'; exit; fi

if [ ! -d "$lpdocs" ]; then
	echo 'Please run:\necho "lpdocs=\$(cd .. && git clone git@github.com:LeonardPauli/docs.git && pwd)/docs" >> .env && ./dev'
	sleep 1; exit; fi

"$lpdocs/app/misc/workspace_setup.sh" "$dev_window_setup" <<-EOF
	{type: "sublime", h: p's h, w: p's w / 2}
	{type: "finder", x: p's w / 2, h: p's h, w: p's w / 2}
	{type: "iterm", in_new: "tab", cmd: "pwd"}
	{type: "iterm", in_new: "v_panel", cmd: "git status", m_down: 9}
EOF
# {type: "finder", h: p's h / 2, w: p's w / 3}
# {type: "finder", x: p's w / 3, h: p's h / 2, w: p's w / 3, path: "$HOME/desktop"}
echo "closing in 3..."; sleep 3 # to keep iterm happy / suppress fast exit message
