version: '3.6'
services:
  app:
    environment:
      npm_config_registry: "http://verdaccio"
    volumes:
      - ..:/app:delegated
      - ./data/node_modules:/app/node_modules:delegated
      - ~/.npm:/root/.npm:delegated
    networks:
      verdaccio:

networks:
  verdaccio:
    external: true
    name: verdaccio
