#!/usr/bin/env sh
load_env () { [ -f .env ] && for a in $1; do
	export $a="$(cat .env | grep $a= | sed -e "s/.*=//g")"; done; }

load_env "env" # see terminal/lib.sh

if [ "$env" = "dev" ]; then
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
elif [ "$env" = "prod" ]; then
	docker-compose -f docker-compose.yml up -d
else echo "unknown env '$env', check .env"; fi
