version: '3.4'
services:
  app:
    image: $image_name:$env
    build:
      context: ..
      dockerfile: container-dev-cache/Dockerfile
      target: $env
    env_file: .env
    volumes:
      - ./data:/data
